### PR TITLE
Added Hex package manager

### PR DESCRIPTION
**Pull request by zabirauf**
Added the ability to search Hex package manager

### CODE REVIEW

**Comment by willfarrell** [comment]
Thanks for the PR. I have a busy day today. Hope it's okay if I check it out tomorrow.

**Comment by zabirauf** [comment]
Sure. Let me know if anything has to be changed or fixed.

**Comment by zabirauf** [comment]
Any updates on the PR?

**Comment by willfarrell** [comment]
Yep, looks good. Checked it out late last night. Just forgot to hit merge.

**Comment by willfarrell** [comment]
@jeffbyrnes

**Comment by zabirauf** [comment]
Thanks Will.

**Pull request merged**
