### PR TITLE
Update rubgems icon

### PR DESCRIPTION
**Pull request by josselinauguste**

### CODE REVIEW

**Comment by jeffbyrnes** [comment]
@josselinauguste thanks for this! Would you please, however, ensure that both image files are the same size?

**Comment by josselinauguste** [comment]
@jeffbyrnes they are now the same size!

**Comment by jeffbyrnes** [comment]
Fantastic. Thanks so much!

**Comment by jeffbyrnes** [comment]
I’ll cut a new release shortly.

**Comment by willfarrell** [comment]
Thanks guys!

**Pull request merged**
