### PR TITLE
Fix php for macOS Monterey

### PR DESCRIPTION
**Pull request by elalemanyo**
Checks for PHP location to handle differences between Intel/M1 macs running Monterey.

Instead of running things like this:
```php
php ./bin/index.php bower {query}
```

we now do:

```php
if [ -f "/opt/homebrew/bin/php" ]; then
	/opt/homebrew/bin/php ./bin/index.php bower {query}
elif [ -f "/usr/local/bin/php" ]; then
    /usr/local/bin/php ./bin/index.php bower {query}
elif [ -f "/usr/bin/php" ]; then
    /usr/bin/php ./bin/index.php bower {query}
fi
```

Not sure if this is the best way but fixes the problem.

willfarrell/alfred-pkgman-workflow/issues/157

**UPDATE**
After @jeffbyrnes comments I decide to do it simpler, now all php calls use  env `$PHP_BIN`, each user can set it as needed. I test it locally and works great.

```php
$PHP_BIN ./bin/index.php bower {query}
```

image

### CODE REVIEW

**Comment by jeffbyrnes** [comment]
This can be condensed to

```bash
if [ -x "/opt/homebrew/bin/php" ]; then
    $PHP_BIN = /opt/homebrew/bin/php
elif [ -x "/usr/local/bin/php" ]; then
    $PHP_BIN = /usr/local/bin/php
elif [ -x "/usr/bin/php" ]; then
    $PHP_BIN = /usr/bin/php
fi

$PHP_BIN ./bin/index.php bower {query}
```

Also, switch from `-f` to `-x` to ensure that the path in question not only exists & is a file, but is executable.

**Comment by elalemanyo** [comment]
> This can be condensed to
> 
> ```shell
> if [ -x "/opt/homebrew/bin/php" ]; then
>     $PHP_BIN = /opt/homebrew/bin/php
> elif [ -x "/usr/local/bin/php" ]; then
>     $PHP_BIN = /usr/local/bin/php
> elif [ -x "/usr/bin/php" ]; then
>     $PHP_BIN = /usr/bin/php
> fi
> 
> $PHP_BIN ./bin/index.php bower {query}
> ```
> 
> Also, switch from `-f` to `-x` to ensure that the path in question not only exists & is a file, but is executable.

@jeffbyrnes I get this error with your code suggestion:
image

**Comment by jeffbyrnes** [comment]
Trust me to typo this 🤦🏻‍♂️ 

Edited the original to be correct.

**Comment by jeffbyrnes** [comment]
Or… not… might have (re)learned a bash nuance…

**Comment by jeffbyrnes** [comment]
Right… spaces are meaningful when assigning variables. Derp! All fixed & really works now, sorry about that.

**Comment by jeffbyrnes** [comment]
That said, I _think_ Alfred is now, as of the most recent version, set to do this internally if you use a relative `php` command in your workflows.

**Comment by elalemanyo** [comment]
@jeffbyrnes would be a bad idea to do it maybe simpler:
image

I am using now Alfred 4.6.1 and was not working for me 🤷‍♂️

**Comment by jeffbyrnes** [comment]
Well now that’s an idea! Though it does leave it up to the end-user to know where their copy of PHP, if any, is installed.

**Comment by elalemanyo** [comment]
> Well now that’s an idea! Though it does leave it up to the end-user to know where their copy of PHP, if any, is installed.

yes, that is true. But this is a workflow for developers, so this should not be a big issue. Just open a terminal and write `which php`

**Review by dioxide — APPROVED** [review]
It works  fine on Monterey.

**Comment by learn2reid** [comment]
Can also update the PATH variable in environment variable & you won't have to change any of the other values

**Comment by varp** [comment]
@jeffbyrnes When this will come up to the master?

**Comment by varp** [comment]
> Can also update the PATH variable in environment variable & you won't have to change any of the other values. ex)
> 
> ```
> PATH: /usr/local/bin:/usr/local/sbin:~/bin
> ```

@learn2reid Could give us more explanation about where do we set PATH env vars? In each script invocation in the workflow?

**Comment by jeffbyrnes** [comment]
@varp I haven’t had much time to devote to this lately, but I’ll see what I can do this week.

As for @learn2reid’s suggestion, if the workflow is using the unqualified `php`, so long as your `$PATH` is set to include wherever you have `php` installed, it _should_ work (but that needs to be verified).

I’ll try that, first, before we go adding complications, and thus fragility, to the workflow.

**Comment by jeffbyrnes** [comment]
Ok, a quick test: it seems that Alfred runs scripts & don’t inherit `$PATH` from the current user. However, adding a `$PATH` env var to the workflow & setting it _does_ work. That’s less fragile & less of a change than what’s been proposed here with the `$PHP_BIN_PATH`, so I think that’s the best way forward right now?

image

**Comment by varp** [comment]
> Ok, a quick test: it seems that Alfred runs scripts & don’t inherit `$PATH` from the current user. However, adding a `$PATH` env var to the workflow & setting it _does_ work. That’s less fragile & less of a change than what’s been proposed here with the `$PHP_BIN_PATH`, so I think that’s the best way forward right now?
> 
> image

@jeffbyrnes Firstly , thank you! 
@elalemanyo I totally agree with @jeffbyrnes. I think use of `$PATH` less fragile and more common and standard approach to execute binaries from custom paths

**Comment by elalemanyo** [comment]
> > Ok, a quick test: it seems that Alfred runs scripts & don’t inherit `$PATH` from the current user. However, adding a `$PATH` env var to the workflow & setting it _does_ work. That’s less fragile & less of a change than what’s been proposed here with the `$PHP_BIN_PATH`, so I think that’s the best way forward right now?
> > image
> 
> @jeffbyrnes Firstly , thank you! @elalemanyo I totally agree with @jeffbyrnes. I think use of `$PATH` less fragile and more common and standard approach to execute binaries from custom paths

@varp yes, I agree. The solution from @jeffbyrnes is better. Feel free to close this PR.
Thanks @jeffbyrnes.

**Comment by jeffbyrnes** [comment]
Alright! Glad that works well folks.

**Comment by varp** [comment]
@jeffbyrnes I've just tested your suggested solution with path `/usr/local/bin:$PATH`. 
One thing I should notice, is that Alfred doesn't support $VAR substitution, so you need to specify also standard locations (you can get it from /etc/paths) `/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin` for do not break invocation of core utils like: mkdir for bash scripts

**Comment by learn2reid** [comment]
@jeffbyrnes glad it worked for others too.

@varp Yes, if you refer back to my original comment with my solution, I did not add $PATH to the variable. I just added the PATH from login invocation.

> Can also update the PATH variable in environment variable & you won't have to change any of the other values. ex)
> 
> ```
> PATH: /usr/local/bin:/usr/local/sbin:~/bin
> ```

**Pull request closed without merging**
